### ISSUE TITLE
points on canvas are not scaling properly

### ISSUE THREAD

**Issue by Antoinebr** [tlouth19/analyze.golf#1]
Hi, 
First of all your app is very cool ! I really like it 💪👍

I noticed that when the viewport changes the points on the canvas are not moving : 

![azB0XBmlRt](https://user-images.githubusercontent.com/8248256/59192479-7ebb8400-8b7a-11e9-816d-544f26830aa0.gif)

**Comment by tlouth19** [comment]
@Antoinebr better late than never right..

I rebuilt the app with vite/react/redux/tailwind, and this issue should be fixed now (although its not working great with orientation change yet)
